
name: Build & Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
        CI: false
        
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
            node-version: 18
      
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
            host: ${{ secrets.SSH_HOST }}
            key: ${{ secrets.SSH_KEY }}
            username: ${{ secrets.SSH_USERNAME }}
            source: /*
            target: ~/sample-repo/html/
            strip_components: 1

      - name: Deploy successfully
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/sample-repo/
            sudo apt-get update
            sudo apt install nodejs npm
            npm install
            npm run start

